# Generated by Django 4.2.6 on 2023-10-23 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=50)),
                ('question_topic', models.CharField(max_length=30)),
                ('question_language', models.CharField(max_length=20)),
                ('question_body', models.TextField()),
                ('question_date', models.DateField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_content', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('name1', models.CharField(max_length=20)),
                ('name2', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name1', models.CharField(max_length=20)),
                ('last_name2', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField()),
                ('institution', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_body', models.TextField()),
                ('answer_date', models.DateField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_content', models.BinaryField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=50)),
                ('project_language', models.CharField(max_length=20)),
                ('project_topic', models.CharField(max_length=30)),
                ('project_description', models.TextField()),
                ('project_upload_date', models.DateField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_content', models.BinaryField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.usuario'),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('archivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo_name', models.CharField(max_length=255)),
                ('archivo_type', models.CharField(max_length=50)),
                ('archivo_content', models.BinaryField()),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.pregunta')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.proyecto')),
                ('respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.respuesta')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.usuario')),
            ],
        ),
    ]
