# Generated by Django 4.2.7 on 2023-11-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdevconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='question_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='project_upload_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='answer_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
