# Generated by Django 4.2.6 on 2023-10-23 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdevconnect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='file_content',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='file_content',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='file_content',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='archivo',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.pregunta'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.proyecto'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appdevconnect.respuesta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
