# Generated by Django 4.2.6 on 2023-11-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdevconnect', '0003_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='file_name',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='preview_image',
            field=models.URLField(blank=True),
        ),
    ]
