# Generated by Django 4.2.7 on 2023-11-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdevconnect', '0004_remove_proyecto_file_name_proyecto_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='archivo_content',
            field=models.URLField(blank=True),
        ),
    ]
